# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import banking_pb2 as banking__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in banking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankingServiceStub(object):
    """Define the BankingService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/banking.BankingService/GetBalance',
                request_serializer=banking__pb2.Empty.SerializeToString,
                response_deserializer=banking__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.PerformTransaction = channel.unary_unary(
                '/banking.BankingService/PerformTransaction',
                request_serializer=banking__pb2.TransactionRequest.SerializeToString,
                response_deserializer=banking__pb2.TransactionResponse.FromString,
                _registered_method=True)


class BankingServiceServicer(object):
    """Define the BankingService
    """

    def GetBalance(self, request, context):
        """Get the current balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformTransaction(self, request, context):
        """Perform a transaction (deposit or withdrawal)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=banking__pb2.Empty.FromString,
                    response_serializer=banking__pb2.BalanceResponse.SerializeToString,
            ),
            'PerformTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformTransaction,
                    request_deserializer=banking__pb2.TransactionRequest.FromString,
                    response_serializer=banking__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.BankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.BankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankingService(object):
    """Define the BankingService
    """

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/GetBalance',
            banking__pb2.Empty.SerializeToString,
            banking__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerformTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/PerformTransaction',
            banking__pb2.TransactionRequest.SerializeToString,
            banking__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
